(ns aoc.day7-test 
  (:require
   [aoc.day7 :as day7]
   [clojure.test :refer [deftest is testing]]))

(def example-data
  ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............")

(deftest analyze-manifold-test
      (testing "part one final solution"
        (is (= 21 (day7/analyze-manifold example-data))))) 

(deftest count-timelines-test
  (testing "part two final solution"
    (is (= 40 (day7/count-timelines example-data)))))
